import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString, Matches, MaxLength, MinLength } from 'class-validator';
import { TrimString } from '../../methods/dto/transforms';

export const PRESENCE_VISITOR_ID_MAX_LENGTH = 100;
const PRESENCE_VISITOR_ID_PATTERN = /^[A-Za-z0-9._:-]+$/;

export class HeartbeatDto {
  @ApiPropertyOptional({
    description:
      'Stable anonymous visitor identifier generated by the frontend. Reused across tabs to avoid duplicate presence counting.',
    example: '550e8400-e29b-41d4-a716-446655440000',
    maxLength: PRESENCE_VISITOR_ID_MAX_LENGTH,
  })
  @IsOptional()
  @TrimString()
  @IsString()
  @MinLength(1)
  @MaxLength(PRESENCE_VISITOR_ID_MAX_LENGTH)
  @Matches(PRESENCE_VISITOR_ID_PATTERN, {
    message: 'visitorId may only contain letters, numbers, dot, underscore, colon or dash',
  })
  visitorId?: string;
}
